trigger:
- master

pool:
  vmImage: 'macOS-latest'

variables:
    buildConfiguration: 'Release'

jobs:
- job: sonar
  displayName: Analyse code with SonarQube

  steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis'
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'aqualityautomation'
      projectKey: 'aquality-automation_aquality-appium-mobile-dotnet-template'
      projectName: 'aquality-appium-mobile-dotnet-template'
      projectVersion: '$(Build.BuildNumber)'
      extraProperties: |
        sonar.coverage.exclusions=**/**
  
  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    env: 
      MSBUILDSINGLELOADCONTEXT: 1  # https://github.com/SpecFlowOSS/SpecFlow/issues/1912
    inputs:
      command: 'build'
      projects: Aquality.Appium.Mobile.Template/Aquality.Appium.Mobile.Template.sln
      arguments: -c $(buildConfiguration)

  - task: SonarCloudAnalyze@1
    displayName: 'Run SonarCloud code analysis'
    continueOnError: true

  - task: SonarCloudPublish@1
    displayName: 'Publish SonarCloud quality gate results'

- job: tests
  displayName: Run tests
  strategy:
    maxParallel: 2
    matrix:
      ANDROID:
        platformName: android
        ANDROID_EMU_NAME: test
        ANDROID_SDK_ID: system-images;android-28;google_apis_playstore;x86
      IOS:
        platformName: ios
        IOS_SIM_ID: iPhone-11, 13.7

  steps:
  - task: CmdLine@2
    displayName: 'Configuring Appium'
    inputs:
      script: |
        echo "Configuring Environment"
        export PATH=$PATH:$JAVA_HOME/bin
        echo export "ANDROID_HOME=\$ANDROID_HOME" >> ~/.bash_profile
        export PATH=$PATH:$ANDROID_HOME

        echo "ANDROID_HOME: ${ANDROID_HOME}"
        echo "JAVA_HOME: ${JAVA_HOME}"
        echo "PATH: ${PATH}"

        echo "Installing Appium"
        npm install -g appium@v1.17.0
        ln -fs /usr/local/lib/node_modules/appium/build/lib/main.js /usr/local/bin/appium
        chmod +x /usr/local/bin/appium
        export PATH=$PATH:/usr/local/bin/appium
        appium --version
        echo "Appium installed"

        echo "Installing and Running Appium doctor"
        npm install -g request@2.34.0
        npm install -g appium-doctor@1.15.1
        ln -fs /usr/local/lib/node_modules/appium-doctor/appium-doctor.js /usr/local/bin/appium-doctor
        chmod +x /usr/local/bin/appium-doctor
        export PATH=$PATH:/usr/local/bin/appium-doctor
        appium-doctor
        echo "Appium doctor installed and executed"

  - task: CmdLine@2
    displayName: 'Configure and start Android emulator'
    inputs:
      script: |
        echo "ANDROID_HOME: ${ANDROID_HOME}"
        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "$(ANDROID_SDK_ID)"
        echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n "$(ANDROID_EMU_NAME)" -k "$(ANDROID_SDK_ID)" -f
        $ANDROID_HOME/emulator/emulator -list-avds

        nohup $ANDROID_HOME/emulator/emulator -avd "$(ANDROID_EMU_NAME)" -no-snapshot > /dev/null 2>&1 &
        $ANDROID_HOME/platform-tools/adb wait-for-device
        while [[ $? -ne 0 ]]; do sleep 1; $ANDROID_HOME/platform-tools/adb shell pm list packages; done;
        $ANDROID_HOME/platform-tools/adb devices
    condition: and(succeeded(), eq(variables['platformName'], 'android'))

  - task: CmdLine@2
    displayName: 'Configure and start iOS simulator'
    inputs:
      script: |
        npm install -g ios-sim@9.0.0
        ios-sim showdevicetypes
        ios-sim start --devicetypeid "$(IOS_SIM_ID)"
        echo "Wait for simulator to be ready"
        sleep 240
    condition: and(succeeded(), eq(variables['platformName'], 'ios'))

  - task: CmdLine@2
    displayName: 'Start Appium server'
    inputs:
      script: |
        appium --allow-insecure chromedriver_autodownload &
        echo "Appium server started"
    condition: succeeded()

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    env: 
      isRemote: true
      MSBUILDSINGLELOADCONTEXT: 1  # https://github.com/SpecFlowOSS/SpecFlow/issues/1912
    inputs:
      command: 'test'
      projects: '**/Aquality.Appium.Mobile.Template.SpecFlow.csproj'
      arguments: -c $(buildConfiguration)
      publishTestResults: true

  - task: CopyFiles@2
    displayName: 'Copy failure screenshots and test logs'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
          **/*SpecFlow*/Screenshots/*.png
          **/*SpecFlow*/Log/*.log
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish copied artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop_$(platformName)'
      publishLocation: 'Container'
    condition: succeededOrFailed()