<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Environment\Prod\config.json" />
    <None Remove="Resources\Environment\Stage\config.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Environment\Prod\config.json" />
    <EmbeddedResource Include="Resources\Environment\Stage\config.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Allure.Net.Commons" Version="2.14.1" />
    <PackageReference Include="Allure.SpecFlow" Version="2.14.1" />
    <PackageReference Include="Aquality.Appium.Mobile" Version="6.2.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Applications\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Applications\TheApp-v1.10.0.apk">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Applications\TheApp-v1.10.0.app.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\devices.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
